# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               -Renk- Takım
tagline:             'R 338 Proje Grubu'
description:         'Akademik Bilişim 2016 - R ile Veri Analizi kursunun Takım -Renk-e ait proje sayfasıdır.'
url:                 http://lanyon.getpoole.com
baseurl:             '/renk-takim'
paginate:            5

# About/contact
author:
  name:              Takım Adı
  url:               
  email:             

# Custom vars
version:             1.0.0
